apiVersion: v1
kind: Service
metadata:
  name: nginx-stateless
spec:
  type: LoadBalancer
  selector:
    app: nginx
    project: roboshop
    component: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: "{ .Values.service.port }"
    targetPort: http-web-svc # this port belongs to container